name: ArenaOfGlory
version: ${version}
main: ru.mainmayhem.arenaofglory.ArenaOfGlory
api-version: 1.16
commands:
  arenahelp:
    description: Отображает все команды с описанием
  arenachoosefraction:
    description: Выбор фракции
  arenachangefraction:
    description: Смена фракции
  arenaenterwaitingroom:
    description: Войти в комнату ожидания
  arenaquitwaitingroom:
    description: Выйти из комнаты ожидания
  arenareloadplugin:
    description: Перезагружает плагин
