name: ArenaOfGlory
version: 1.0
main: ru.mainmayhem.arenaofglory.ArenaOfGlory
api-version: 1.16
commands:
  arenahelp:
    description: Отображает все команды с описанием
  arenachoosefraction:
    description: Выбор фракции
  arenachangefraction:
    description: Смена фракции
